language: node_js
node_js: stable
sudo: required

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install js-yaml --save-dev
  - npm install nodejieba --save-dev

script:
  - hexo clean
  - hexo g
  
branches:
  only:
    - 1.3
